### ISSUE TITLE
js, kalender dagens dag visar fortfarande en annan färg fast man kommer till år 2022

### ISSUE THREAD

**Issue by maxAndersson** [FrontFelix/MiniP#1]

**Comment by FrontFelix** [comment]
Ändrade `if (i === new Date().getDate() && date.getMonth() === new Date().getMonth())` 
till `(i === new Date().getDate() && date.getMonth() === new Date().getMonth() && date.getFullYear() === new Date().getFullYear())`
 så att den också kollar vilket år det är.  Då visar bara dagens datum upp med annan färg även om man byter år
