### ISSUE TITLE
titel

### ISSUE THREAD

**Issue by maxAndersson** [FrontFelix/MiniP#6]
Få Kalender att hamna rätt position till h1 december

**Comment by FrontFelix** [comment]
Kan bli svårt, pågrund av att vi har 2 olika containrar som är flexade.

Kalender just nu ligger centrad i mitten av sin `div` men vi kanske kan kolla om vi kan komma på någon smart lösning med `margin-left`? Kanske hård-koda ett `value` som ligger nära Kalender `h1`:an
